package OneLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;

public class Date_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    String testValue = null;
    if (value == null) {
      testValue = "";
    } else {
      testValue = value;
    }
    return testValue.matches("\\d{2}-\\d{2}-\\d{4}");
  }
}
