package OneLang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum Gender {
  male("Male", "male"),
  female("Female", "female"),
  unknown("Unknown", "unknown");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private Gender(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<Gender> getConstants() {
    List<Gender> list = ListSequence.fromList(new LinkedList<Gender>());
    ListSequence.fromList(list).addElement(Gender.male);
    ListSequence.fromList(list).addElement(Gender.female);
    ListSequence.fromList(list).addElement(Gender.unknown);
    return list;
  }
  public static Gender getDefault() {
    return Gender.male;
  }
  public static Gender parseValue(String value) {
    if (value == null) {
      return Gender.getDefault();
    }
    if (value.equals(Gender.male.getValueAsString())) {
      return Gender.male;
    }
    if (value.equals(Gender.female.getValueAsString())) {
      return Gender.female;
    }
    if (value.equals(Gender.unknown.getValueAsString())) {
      return Gender.unknown;
    }
    return Gender.getDefault();
  }
}
