package OneLang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum GeoArea {
  Worldwide("Worldwide", "worldwide"),
  Asia("Asia", "asia"),
  Worldwide_excluding_USA("Worldwide excluding USA", "worldwide excluding USA");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private GeoArea(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<GeoArea> getConstants() {
    List<GeoArea> list = ListSequence.fromList(new LinkedList<GeoArea>());
    ListSequence.fromList(list).addElement(GeoArea.Worldwide);
    ListSequence.fromList(list).addElement(GeoArea.Asia);
    ListSequence.fromList(list).addElement(GeoArea.Worldwide_excluding_USA);
    return list;
  }
  public static GeoArea getDefault() {
    return null;
  }
  public static GeoArea parseValue(String value) {
    if (value == null) {
      return GeoArea.getDefault();
    }
    if (value.equals(GeoArea.Worldwide.getValueAsString())) {
      return GeoArea.Worldwide;
    }
    if (value.equals(GeoArea.Asia.getValueAsString())) {
      return GeoArea.Asia;
    }
    if (value.equals(GeoArea.Worldwide_excluding_USA.getValueAsString())) {
      return GeoArea.Worldwide_excluding_USA;
    }
    return GeoArea.getDefault();
  }
}
