package OneLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;
import java.util.Iterator;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class HospitalCoverage_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    if (value == null) {
      return true;
    }
    Iterator<HospitalCoverage> constants = ListSequence.fromList(HospitalCoverage.getConstants()).iterator();
    while (constants.hasNext()) {
      HospitalCoverage constant = constants.next();
      if (value.equals(constant.getName())) {
        return true;
      }
    }
    return false;
  }
  public String toInternalValue(String value) {
    if (value == null) {
      return null;
    }
    Iterator<HospitalCoverage> constants = ListSequence.fromList(HospitalCoverage.getConstants()).iterator();
    while (constants.hasNext()) {
      HospitalCoverage constant = constants.next();
      if (value.equals(constant.getName())) {
        return constant.getValueAsString();
      }
    }
    return null;
  }
  public String fromInternalValue(String value) {
    HospitalCoverage constant = HospitalCoverage.parseValue(value);
    if (constant != null) {
      return constant.getName();
    }
    return "N/A";
  }
}
