package OneLang.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Customer = 0;
  public static final int Eligibility = 1;
  public static final int HealthBenefit = 2;
  public static final int HealthCharge = 3;
  public static final int IChargeable = 4;
  public static final int Plan = 5;
  public static final int PolicyWording = 6;
  public static final int Product = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc4bcb11ff1394de7L, 0x844230891be7cfe2L);
    builder.put(0x7c09fe14ad1079f7L, Customer);
    builder.put(0x7c09fe14ad107c6eL, Eligibility);
    builder.put(0x7c09fe14ad107a9eL, HealthBenefit);
    builder.put(0x7c09fe14ad107a8eL, HealthCharge);
    builder.put(0x7aa20b94a761b26aL, IChargeable);
    builder.put(0x7c09fe14ad1079eaL, Plan);
    builder.put(0x7c09fe14ad107c72L, PolicyWording);
    builder.put(0x7c09fe14ad1079d1L, Product);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
