package OneLang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum LoB {
  Health("Health", "health"),
  Life("Life", "life"),
  Home("Home", "home"),
  Travel("Travel", "travel"),
  Motor("Motor", "motor");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private LoB(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<LoB> getConstants() {
    List<LoB> list = ListSequence.fromList(new LinkedList<LoB>());
    ListSequence.fromList(list).addElement(LoB.Health);
    ListSequence.fromList(list).addElement(LoB.Life);
    ListSequence.fromList(list).addElement(LoB.Home);
    ListSequence.fromList(list).addElement(LoB.Travel);
    ListSequence.fromList(list).addElement(LoB.Motor);
    return list;
  }
  public static LoB getDefault() {
    return null;
  }
  public static LoB parseValue(String value) {
    if (value == null) {
      return LoB.getDefault();
    }
    if (value.equals(LoB.Health.getValueAsString())) {
      return LoB.Health;
    }
    if (value.equals(LoB.Life.getValueAsString())) {
      return LoB.Life;
    }
    if (value.equals(LoB.Home.getValueAsString())) {
      return LoB.Home;
    }
    if (value.equals(LoB.Travel.getValueAsString())) {
      return LoB.Travel;
    }
    if (value.equals(LoB.Motor.getValueAsString())) {
      return LoB.Motor;
    }
    return LoB.getDefault();
  }
}
