package OneLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;
import java.util.Iterator;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class Treatment_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    if (value == null) {
      return true;
    }
    Iterator<Treatment> constants = ListSequence.fromList(Treatment.getConstants()).iterator();
    while (constants.hasNext()) {
      Treatment constant = constants.next();
      if (value.equals(constant.getName())) {
        return true;
      }
    }
    return false;
  }
  public String toInternalValue(String value) {
    if (value == null) {
      return null;
    }
    Iterator<Treatment> constants = ListSequence.fromList(Treatment.getConstants()).iterator();
    while (constants.hasNext()) {
      Treatment constant = constants.next();
      if (value.equals(constant.getName())) {
        return constant.getValueAsString();
      }
    }
    return null;
  }
  public String fromInternalValue(String value) {
    Treatment constant = Treatment.parseValue(value);
    if (constant != null) {
      return constant.getName();
    }
    return "N/A";
  }
}
