package OneLang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum Treatment {
  Diagnostic_procedures("Diagnostic procedures", "diagnostic procedures"),
  Surgical_procedures("Surgical procedures", "surgical procedures"),
  Operating_theatre_charges("Operating theatre charges", "operating theatre charges"),
  Organ_transplant("Organ transplant", "organ transplant");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private Treatment(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<Treatment> getConstants() {
    List<Treatment> list = ListSequence.fromList(new LinkedList<Treatment>());
    ListSequence.fromList(list).addElement(Treatment.Diagnostic_procedures);
    ListSequence.fromList(list).addElement(Treatment.Surgical_procedures);
    ListSequence.fromList(list).addElement(Treatment.Operating_theatre_charges);
    ListSequence.fromList(list).addElement(Treatment.Organ_transplant);
    return list;
  }
  public static Treatment getDefault() {
    return null;
  }
  public static Treatment parseValue(String value) {
    if (value == null) {
      return Treatment.getDefault();
    }
    if (value.equals(Treatment.Diagnostic_procedures.getValueAsString())) {
      return Treatment.Diagnostic_procedures;
    }
    if (value.equals(Treatment.Surgical_procedures.getValueAsString())) {
      return Treatment.Surgical_procedures;
    }
    if (value.equals(Treatment.Operating_theatre_charges.getValueAsString())) {
      return Treatment.Operating_theatre_charges;
    }
    if (value.equals(Treatment.Organ_transplant.getValueAsString())) {
      return Treatment.Organ_transplant;
    }
    return Treatment.getDefault();
  }
}
